Pmux 1323 cligam cli temp master
dnanexus/dx-toolkit pull request #1003
Opened 2023-04-07 22:00 UTC by JoeMulka

Hi Folks,
This PR introduces functionality for accessing Germline Assay Model data from the command line without needing to manually construct SQL queries.  It relies on the Cohort Browser API (described here: https://github.com/dnanexus/hare/blob/master/docs/API-SpecificationV3.md), and returns data in .tsv format.  The spec document for the project can be found here: https://docs.google.com/document/d/1JfCn7wpX-W3QY4-E4SvmwUnGVLg2fW34DpoO-E4QOx0/edit#heading=h.tfyf7djf1i2p
Additional testing and bugfixes incoming

2023-05-04 09:50 UTC, wormsik requested changes

2023-05-04 09:50 UTC, wormsik commented on src/python/dxpy/cli/dataset_utilities.py
> +        filter_value = str(eval(filter_arg))
consider using to avoid `eval`:
```
filter_value = vars(args)['retrieve_' + filter_type]
```

2023-05-04 10:09 UTC, commandlinegirl requested changes
Please update the title of the PR, according to our convention it should say something like: `PMUX-1323 Short description of the update`. I'll make additional comments in the ticket. Thanks!

2023-05-10 00:43 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +                'Please specify one of the following: --retrieve-allele, --retrieve-genotype or --retrieve-annotation" for details on the corresponding JSON template and filter definition.'
It looks like add_mutually_exclusive_group is deprecated as of version 3.11.  Some stack overflow posts I'm seeing are recommending using subparsers,  but I think "germline" is already a subparser of dx extract_assay, and I'm not sure if its possible or recommended to nest a subparser within another subparser.  The other suggestions I'm seeing on the internet are to just use python logic to detect when mutually exclusive args are present in the args object, similarly to what is being done here.  Should we keep this code as it is?

2023-05-10 19:39 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +            "%r : Invalid path. The path must point to a record type of cohort or dataset"
this could cause a problem if __repr__ isn't implemented for the object being printed right?

2023-05-10 23:11 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +    quote_char=str('"'),
Casting this to string cleared a bug with python 2 compatibility, I was having issues in various places where the python 2 interpreter was using unicode where it should have been using str.  I'm not 100% sure why python 2 was interpreting this as unicode, however.

2023-05-11 05:18 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +                    json_file = open(filter_value)
If we have an err_exit() within the `with open`, will it close the file object before the program terminates, or will it leave it in a broken state?

2023-05-11 05:21 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +                int(model["codings"][coding_name_value]["display"].index(c) + 1)
Its possible that this was a python 2 compatibility thing but I can try removing the `int` and see if it breaks anything

2023-05-11 10:23 UTC, wormsik commented on src/python/dxpy/cli/dataset_utilities.py
> +    quote_char=str('"'),
huh didn't know that...so just leave it as it is...

2023-05-13 00:05 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +            "%r : Invalid path. The path must point to a record type of cohort or dataset"
@keegankelsey should I go ahead and implement this change?

2023-05-13 07:47 UTC, wormsik commented on src/python/dxpy/cli/dataset_utilities.py
> +                    json_file = open(filter_value)
yes it should as sys.exit only throws specific exception...so all the cleanup, finally blocks, etc will be correctly done... https://docs.python.org/3/library/sys.html#sys.exit

2023-05-17 16:31 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +                'Please specify one of the following: --retrieve-allele, --retrieve-genotype or --retrieve-annotation" for details on the corresponding JSON template and filter definition.'
Just merged a PR that uses mutually exclusive groups and gets rid of this check

2023-05-17 17:16 UTC, JoeMulka commented on src/python/dxpy/cli/dataset_utilities.py
> +                    json_file = open(filter_value)
fixed on cligam-with-open branch PR

2023-06-01 01:49 UTC, kpjensen approved these changes

2023-06-01 01:49 UTC, kpjensen commented on src/python/dxpy/exceptions.py
> +    json_exceptions = (json.decoder.JSONDecodeError,)
I think it's fine to add for now as it only affects printing the traceback.

2023-06-02 18:52 UTC, vkuban-dx commented on src/python/dxpy/cli/dataset_utilities.py
> +                '# Filters and respective definitions\n#  allele_id: ID(s) of one or more alleles for which sample genotypes will be returned. If multiple values are provided, any samples having at l
pls, keep the same format for help messages:
```suggestion
                '# Filters and respective definitions\n#\n#  allele_id: ID(s) of one or more alleles for which sample genotypes will be returned. If multiple values are provided, any samples having at least one allele that match any of the values specified will be listed. For example, ["1_1000_A_T", "1_1010_C_T"], will search for samples with at least one allele matching either "1_1000_A_T" or "1_1010_C_T". String match is case insensitive.\n#  sample_id: Optional, one or more sample IDs for which sample genotypes will be returned. If the provided object is a cohort, this further intersects the sample ids. If a user has a list of samples more than 1,000, it is recommended to use a cohort id containing all the samples.\n#  genotype_type: Optional, one or more genotype types for which sample genotype types will be returned. One of: hom-alt (homozygous for the non-ref allele), het-ref (heterozygous with a ref allele and alt allele), het-alt (heterozygous with two distinct alt alleles), half (only one alt allele is known, second allele is unknown).\n# JSON filter template for --retrieve-genotype\n{\n  "sample_id": ["s1", "s2"],\n  "allele_id": ["1_1000_A_T","2_1000_G_C"],\n  "genotype_type": ["het-ref", "hom-alt"]\n}'
```

2023-06-08 18:33 UTC, merged