Pmux 1324 clisam cli temp master
dnanexus/dx-toolkit pull request #1089
Opened 2023-06-26 19:37 UTC by JoeMulka

Hi All,
This change adds CLI support for the somatic assay model.  The spec for this [can be found here](https://docs.google.com/document/d/1UjhTQh_w8iuD3OZ1AJs3WAVuUlx9TKK62bZzcrx3fr0/edit?pli=1)
Additional automated testing is forthcoming
Please feel free to make change requests and leave comments, and also to DM me directly with any questions or requests

2023-06-26 22:18 UTC, keegankelsey commented on src/python/test/test_extract_somatic.py
> +    test_record = "{}:/test_keegan_202306231200".format(test_project)
Should be updated with `test_single_assay_202306231200` @JoeMulka

2023-06-26 22:37 UTC, durae commented on src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
> +        "pheno_filters": {"name": name, "id": id, "logic": "and", "compound": []}
Tomorrow (6/27) we will push to vizserver the update, which will allow to send the filters as `assay_filters` and not `pheno_filters`. However, the change should land on production only on 7/11. Please update the code dependent on the release plan for this feature.
cc: @keegankelsey

2023-07-05 17:34 UTC, kpjensen requested changes
Please revert the 8k lines of linter changes in `dx.py` so that this PR only includes the relevant changes for this feature.

2023-07-06 14:22 UTC, kpjensen approved these changes

2023-07-06 16:41 UTC, durae commented on src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
> +        "pheno_filters": {"name": name, "id": id, "logic": "and", "compound": []}
@JoeMulka can this be changed to use assay_filters properly? The vizserver support is planned to go on production next Tuesday 7/11 so definitely before CLISAM release.

2023-07-06 21:22 UTC, merged