APPS-1794 revert removing sys reqs args in DXExectuable run
dnanexus/dx-toolkit pull request #1120
Opened 2023-07-14 18:21 UTC by YuxinShi0423

This PR is to 

- add back system requirement related arguments `instance_type` and `cluster_spec` to DXExecutable.run
- add `fpga_driver` arg as well, which was missing from previous implementation

2023-07-17 15:34 UTC, commandlinegirl commented
Approved modulo integration test runs pass. Thank you!

2023-07-17 17:33 UTC, r-i-v-a commented
Could the PR also update the changelog file -- both re: the previously released version and the fix version? @YuxinShi0423 @commandlinegirl @kpjensen

2023-07-17 19:25 UTC, YuxinShi0423 commented on src/python/test/test_dxclient.py
> +        def check_instance_count(job_desc , entrypoints , expected_counts):
fix invalid syntax in py2.7

2023-07-17 19:26 UTC, YuxinShi0423 commented on src/python/dxpy/bindings/dxapplet.py
> +        if kwargs.get('instance_type') is not None or kwargs.get('cluster_spec') is not None or kwargs.get('fpga_driver') is not None:
added back `instance_type` and `cluster_spec`

added `fpga_driver`

2023-07-17 23:20 UTC, r-i-v-a commented
Ignore earlier comment about changelog since the code wasn't released yet.

2023-07-18 01:00 UTC, kpjensen requested changes
Have not reviewed code, but please reopen this PR in a new branch with your changes rebased off of the latest master to avoid any confusing history.

2023-07-18 20:34 UTC, closed without merging