APPS-2277 nextaur 1.7.0 update
dnanexus/dx-toolkit pull request #1297
Opened 2023-12-08 00:17 UTC by mhrvol

2023-12-08 13:37 UTC, r-i-v-a approved these changes

2023-12-10 00:11 UTC, mhrvol commented
3 fails - https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/683/console

2 of fails are in master as well - https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/681/console

last fail - There seem to be multiple output files in case of publishDir.

I've tried creating the same workflow with older version of nextaur (which has nextflow 23.10.0) - there was no such problem (https://staging.dnanexus.com/panx/projects/GG76K7j01xy3fZ7zFZ94YBY8/monitor/job/GbpPxB001xy5GByvX7xBfBp1)

But when the same workflow was run with the latest master - There are more files - see https://staging.dnanexus.com/panx/projects/GG76K7j01xy3fZ7zFZ94YBY8/monitor/job/GbpPJZQ01xy5GByvX7xBfBkv

Disregard "build with dxtoolkit version" as I just updated the nextaur in the latest dxpy, so the version remains the same (though nextflow version mentioned in the log is correct)

I am yet to figure out what exactly caused this issue, but it seems that it is one of the commits since 9a842eed328ab676b0279b04ad25c29339e6164e

2023-12-11 15:51 UTC, r-i-v-a approved these changes

2023-12-11 15:53 UTC, r-i-v-a requested changes
Need to update dx-toolkit changelog?

2023-12-11 16:07 UTC, r-i-v-a approved these changes

2023-12-11 16:10 UTC, merged