APPS-2410 release nextaur 1.7.1
dnanexus/dx-toolkit pull request #1309
Opened 2024-01-17 02:08 UTC by YuxinShi0423

2024-01-17 02:38 UTC, YuxinShi0423 commented
https://jenkins-vstg.internal.dnanexus.com/view/dx-toolkit%20release%20board/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/693/

2024-01-18 09:28 UTC, r-i-v-a approved these changes

2024-01-18 10:02 UTC, mhrvol approved these changes
LGTM

2024-01-19 16:55 UTC, r-i-v-a commented on CHANGELOG.md
> +* Released Nextaur 1.7.1. It contains multiple fixes in resolving docker image digests, handling file path collision and OOM when creating new input stream.
Changelog entry should move to unreleased section @YuxinShi0423

2024-01-19 16:56 UTC, r-i-v-a requested changes
Changelog entry should move to unreleased section

2024-01-19 17:01 UTC, r-i-v-a approved these changes
Fixed the changelog entry; please continue with the release.

2024-01-19 17:03 UTC, merged