APPS-1028 Fix cleanup function to support full id when building from
dnanexus/dx-toolkit pull request #753
Opened 2022-01-18 17:41 UTC by YuxinShi0423

2022-01-19 14:03 UTC, r-i-v-a commented
Testing it here https://github.com/dnanexus/dxCompiler/pull/254 @YuxinShi0423

2022-01-19 16:27 UTC, r-i-v-a commented on src/python/dxpy/workflow_builder.py
> +    clean_json = re.sub('\"\w*\": (null|\{\}|\"\"|\[\])(\,|)\s*','',json.dumps(json_spec)).replace(", }","}")
Can this be somehow covered by a unit test? @YuxinShi0423

2022-01-19 16:27 UTC, r-i-v-a requested changes
Can this be somehow covered by a unit test?

2022-01-20 22:18 UTC, YuxinShi0423 commented
https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/115/console
Unit test passed,

2022-01-20 22:45 UTC, kpjensen approved these changes

2022-01-20 22:47 UTC, merged