APPS-1157 symlink download improvements
dnanexus/dx-toolkit pull request #773
Opened 2022-04-20 14:02 UTC by mhrvol

2022-04-20 14:04 UTC, mhrvol commented on src/python/dxpy/bindings/dxfile_functions.py
> +    if symlink_max_tries < 1:
symlink_max_tries is currently checked in the download parser, so there is no way this code will ever be triggered. I added this code just to make sure that if somebody ever uses this, we will never get infinite loop (which would be case for symlink_max_tries == 0 if the file is for some reason 'undownloadable')

2022-04-22 06:55 UTC, commandlinegirl requested changes
Minor requests. Thanks!

2022-04-22 06:55 UTC, commandlinegirl commented on src/python/dxpy/bindings/dxfile_functions.py
> +                    project=None, describe_output=None, symlink_max_tries=False, **kwargs):
The default should not be boolean.

2022-04-22 06:55 UTC, commandlinegirl commented on src/python/dxpy/scripts/dx.py
> +parser_download.add_argument('--symlink-max-tries', help='Set maximum tries for downloading symlinked files using aria2c',
```suggestion
parser_download.add_argument('--symlink-max-tries', help='Set maximum number of tries for downloading symlinked files using aria2c',
```

2022-04-22 06:55 UTC, commandlinegirl commented on CHANGELOG.md
> +* Improvements to symlink downloading reliability by solely using `aria2c` and enhancing options around its use
```suggestion
* Improvements to symlink downloading reliability by solely using `aria2c` and enhancing options around its use (removes `wget` option for downloading symlinked files, adds the ability to set max tries for aria2c, adds `-c` flag for continuing downloads, removes the `--check-certificate=false` option).
```

2022-04-22 07:29 UTC, mhrvol commented on src/python/dxpy/bindings/dxfile_functions.py
> +                    project=None, describe_output=None, symlink_max_tries=False, **kwargs):
Thanks! fixed

2022-04-22 07:59 UTC, commandlinegirl approved these changes
LGTM, thanks!

2022-04-25 08:07 UTC, merged